server:
  port: 8080

spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: GMT+8

  # 多数据源配置
#  datasource:
#    db1:
#      jdbc-url: jdbc:mysql://10.211.55.15:3306/p1?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    db2:
#      jdbc-url: jdbc:mysql://10.211.55.15:3306/p2?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver

  # 使用JTA 事务处理，在多数据源情况下, 顶格
primarydb:
  uniqueResourceName: primary
#  xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://10.211.55.15:3306/p1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: root
    password: 123456
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。
secondarydb:
  uniqueResourceName: secondary
#  xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://10.211.55.15:3306/p2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: root
    password: 123456
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。

#
#