spring:
  application:
    name: hello-spring-boot
  thymeleaf:
    # 开发时关闭缓存，不然没法看到实施页面
    cache: false
    # 非严格HTML
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.15:3306/kasaya?useUnicode=true&characterEncoding=utf-8&useSSL=false
    data-username: root
    data-password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT

mybatis:
  type-aliases-package: com.ocoyue.cloud.p1.domain
  mapper-locations: classpath:mapper/*.xml




server:
  port: 8081
  servlet:
    context-path: /boot

logging:
  # 此处的当前目录是kasaya
  file: ./logs/p1.log
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: DEBUG








